-- smazání tabulek včetně všech referenčních integritních omezení, které by tomu bránily
DROP TABLE DODAVA CASCADE CONSTRAINTS;
DROP TABLE LEK CASCADE CONSTRAINTS;
DROP TABLE VLASTNI CASCADE CONSTRAINTS;
DROP TABLE VYROBCE CASCADE CONSTRAINTS;
DROP TABLE SMLOUVA CASCADE CONSTRAINTS;
DROP TABLE DODAVATEL CASCADE CONSTRAINTS;
DROP TABLE NAKUPUJE CASCADE CONSTRAINTS;
DROP TABLE ZAKAZNIK CASCADE CONSTRAINTS;
DROP TABLE ZAMESTNANEC CASCADE CONSTRAINTS;
DROP TABLE LEKARNA CASCADE CONSTRAINTS;

--smazani pohledu
DROP VIEW DODAVKY_V_ZIME_POD_20_LEKU;
DROP VIEW LEKARNA_VLASTNICI_PARALEN;
DROP VIEW SMLOUVY_EXPIRUJICI_PO_ROCE_2027;
DROP VIEW NAKUPY;