CREATE TABLE LEKARNA(
    c_lekarny INTEGER NOT NULL,
    adresa_lekarny VARCHAR2(50) NOT NULL,
    nazev_lekarny VARCHAR2(50) NOT NULL
);
ALTER TABLE LEKARNA ADD CONSTRAINT LEKARNA_PK PRIMARY KEY (c_lekarny);

CREATE TABLE ZAMESTNANEC(
    c_zamestnance INTEGER NOT NULL,
    jmeno_zamestnance VARCHAR2(50) NOT NULL,
    prijmeni_zamestnance VARCHAR2(50) NOT NULL, 
    rc_zamestnance VARCHAR2(10),
    LEKARNA_c_lekarny INTEGER NOT NULL  
);

create Table ZAKAZNIK(
c_zakaznika INTEGER NOT NULL,
jmeno_zakaznika VARCHAR2(50) NOT NULL,
prijmeni_zakaznika VARCHAR2(50) NOT NULL,
rc_zakaznika VARCHAR2(10)
);

CREATE TABLE NAKUPUJE(
c_nakupu INTEGER NOT NULL,
datum_nakupu DATE NOT NULL,
ZAKAZNIK_c_zakaznika INTEGER NOT NULL,
LEKARNA_c_lekarny INTEGER NOT NULL
);

CREATE TABLE DODAVATEL(
    c_dodavatele INTEGER NOT NULL,
    nazev_dodavatele VARCHAR2(50) NOT NULL,
    adresa_dodavatele VARCHAR2(50) NOT NULL
);

CREATE TABLE VYROBCE(
c_vyrobce INTEGER NOT NULL,
nazev_vyrobce VARCHAR2(50) NOT NULL,
adresa_vyrobce VARCHAR2(50) NOT NULL
);

CREATE TABLE LEK(
c_leku INTEGER NOT NULL,
nazev_leku VARCHAR2(50) NOT NULL,
druh_leku VARCHAR2(30),
VYROBCE_c_vyrobce INTEGER NOT NULL  
);

CREATE TABLE DODAVA(
c_dodavky INTEGER NOT NULL,
d_dodani DATE NOT NULL,
mnozstvi INTEGER NOT NULL,
DODAVATEL_c_dodavatele INTEGER NOT NULL,
LEK_c_leku INTEGER NOT NULL
);

CREATE TABLE SMLOUVA(
id_smlouvy INTEGER NOT NULL,
d_podepsani DATE NOT NULL,
d_expirace DATE NOT NULL,
LEKARNA_c_lekarny INTEGER NOT NULL,
DODAVATEL_c_dodavatele INTEGER NOT NULL
);

CREATE TABLE VLASTNI(
pocet INTEGER NOT NULL,
LEKARNA_c_lekarny INTEGER NOT NULL,
LEK_c_leku INTEGER NOT NULL
);

ALTER TABLE ZAMESTNANEC ADD CONSTRAINT ZAMESTNANEC_PK PRIMARY KEY (c_zamestnance);

ALTER TABLE ZAKAZNIK ADD CONSTRAINT ZAKAZNIK_PK PRIMARY KEY (c_zakaznika);

ALTER TABLE NAKUPUJE ADD CONSTRAINT NAKUPUJE_PK PRIMARY KEY (c_nakupu);

ALTER TABLE VLASTNI ADD CONSTRAINT VLASTNI_PK PRIMARY KEY (pocet, LEKARNA_c_lekarny, LEK_c_leku);

ALTER TABLE SMLOUVA ADD CONSTRAINT SMLOUVA_PK PRIMARY KEY (id_smlouvy);

ALTER TABLE DODAVATEL ADD CONSTRAINT DODAVATEL_PK PRIMARY KEY (c_dodavatele);

ALTER TABLE DODAVA ADD CONSTRAINT DODAVA_PK PRIMARY KEY (c_dodavky);

ALTER TABLE LEK ADD CONSTRAINT LEK_PK PRIMARY KEY (c_leku);

ALTER TABLE VYROBCE ADD CONSTRAINT VYROBCE_PK PRIMARY KEY (c_vyrobce);

ALTER TABLE LEK ADD CONSTRAINT LEK_VYROBCE_FK FOREIGN KEY (VYROBCE_c_vyrobce) REFERENCES VYROBCE(c_vyrobce);

ALTER TABLE DODAVA ADD CONSTRAINT DODAVA_DODAVATEL_FK FOREIGN KEY (DODAVATEL_c_dodavatele) REFERENCES DODAVATEL(c_dodavatele);

ALTER TABLE DODAVA ADD CONSTRAINT DODAVA_LEK_FK FOREIGN KEY (LEK_c_leku) REFERENCES LEK(c_leku);

ALTER TABLE VLASTNI ADD CONSTRAINT VLASTNI_LEK_FK FOREIGN KEY (LEK_c_leku) REFERENCES LEK(c_leku);

ALTER TABLE VLASTNI ADD CONSTRAINT VLASTNI_LEKARNA_FK FOREIGN KEY (LEKARNA_c_lekarny) REFERENCES LEKARNA(c_lekarny);

ALTER TABLE SMLOUVA ADD CONSTRAINT SMLOUVA_LEKARNA_FK FOREIGN KEY (LEKARNA_c_lekarny) REFERENCES LEKARNA(c_lekarny);

ALTER TABLE SMLOUVA ADD CONSTRAINT SMLOUVA_DODAVATEL_FK FOREIGN KEY (DODAVATEL_c_dodavatele) REFERENCES DODAVATEL(c_dodavatele);

ALTER TABLE ZAMESTNANEC ADD CONSTRAINT ZAMESTNANEC_LEKARNA_FK FOREIGN KEY (LEKARNA_c_lekarny) REFERENCES LEKARNA(c_lekarny);

ALTER TABLE NAKUPUJE ADD CONSTRAINT NAKUPUJE_LEKARNA_FK FOREIGN KEY (LEKARNA_c_lekarny) REFERENCES LEKARNA(c_lekarny);

ALTER TABLE NAKUPUJE ADD CONSTRAINT NAKUPUJE_ZAKAZNIK_FK FOREIGN KEY (ZAKAZNIK_c_zakaznika) REFERENCES ZAKAZNIK(c_zakaznika);
